### PR TITLE
update npm packages

### LINKED ISSUE #24: npm packages outdated
#### Description
It seems that the npm packages have been outdated and needs updation

#### Screenshots
Screenshot from 2019-05-05 16-38-37

#### Files which needs Updation
* `package.json`
* `package-lock.json`

#### To Reproduce
Clone the repo then,
```
$ cd blog/
$ npm outdated
```

#### Additional Information
Beginners could take up this issue.

### PR DESCRIPTION
**Pull request by AdityaSrivast**
Fixes: #24 
@ryzokuken Please review

### CODE REVIEW

**Comment by ryzokuken** [comment]
I see major upgrades. Did you verify that the site works with these changes? I wouldn't believe so.

/cc @Yugandhartripathi

**Comment by Yugandhartripathi** [comment]
@AdityaSrivast can you share screenshots for the following:
- <code>npm outdated</code>
- <code>npm audit</code>
- <code>gatsby develop</code>

I don't think this will work as package.json is missing react which would have been fine with gatsby v1 as react package was part of gatsby package but now it's a peer dependency.

**Comment by Yugandhartripathi** [comment]
You can refer official migration doc [here](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2).

**Comment by AdityaSrivast** [comment]
> You can refer official migration doc [here](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2).

@Yugandhartripathi thanks! Will have a look and update the PR accordingly by evening

**Comment by saranshbarua** [comment]
@AdityaSrivast are you still working on this? This PR looks inactive. You can consult @Yugandhartripathi if you're stuck.

**Comment by sidntrivedi** [comment]
Should we close this since its inactive for a while.

/cc: @ryzokuken @saranshbarua

**Comment by AdityaSrivast** [comment]
Closing it as I won't be able to work on it currently.

**Pull request closed without merging**
