### PR TITLE
Added blog for Intro-to-Vim

### PR DESCRIPTION
**Pull request by nightwarriorftw**

### CODE REVIEW

**Comment by saranshbarua** [comment]
cc @vaibhavk

**Comment by vnzongzna** [comment]
@nightwarrior-xxx  Please add a reference to https://vim.rtorr.com/ for a quick intro or to keep as a cheat-cheet, will be helpful.
Also you forgot to add the important `verbs` I told like `inside` or `i` with any of the editing commands.
`%` for jumping to matching tags (in Neovim) or matching parenthesis (Vim)
`=` to indent the block

**Comment by nightwarriorftw** [comment]
@vaibhavk Sorry my bad, will add them too.

**Comment by ryzokuken** [comment]
Ping @nightwarrior-xxx

**Comment by nightwarriorftw** [comment]
pong @ryzokuken . Will do required changes by tomorrow.

**Comment by nightwarriorftw** [comment]
@ryzokuken @vaibhavk  Please review

**Comment by vnzongzna** [comment]
@nightwarrior-xxx  I see that you added indent features, still missing inside (```i```).
LGTM anyways.
cc @ryzokuken

**Review by ryzokuken — APPROVED** [review]
@vaibhavk looks good?

**Pull request merged**
