### PR TITLE
Updated wanna-play-linux-meetup0 /index.md

### PR DESCRIPTION
**Pull request by mprakhar1705**
Fixed typos and whitespaces.

### CODE REVIEW

**Review by ryzokuken — CHANGES_REQUESTED** [review]
`wargame` is the correct spelling here, other changes are perfect.

**Comment by vnzongzna** [comment]
@ryzokuken @tonystark97 ping

**Comment by ryzokuken** [comment]
Does someone else want to jump in and fix this?

**Comment by codekhal** [comment]
@ryzokuken Sure, except typos is there something else to be done?

**Comment by ryzokuken** [comment]
Closed in favor of https://github.com/osdc/blog/pull/23

**Pull request closed without merging**
