### PR TITLE
Replaced Club with Community.

### PR DESCRIPTION
**Pull request by sidntrivedi**

### CODE REVIEW

**Comment by sidntrivedi** [comment]
@ryzokuken Just a minor change. PTAL.

**Review by ryzokuken — CHANGES_REQUESTED** [review]
Looks great, but seems to have a weird whitespace issue. Please fix that.

**Comment by sidntrivedi** [comment]
@ryzokuken Ok. Will fix it and commit asap.

**Comment by sidntrivedi** [comment]
Since, this was solved in #8. So, closing it. Thanks.

**Pull request closed without merging**
