### PR TITLE
Revamped blog from Gatsby v1 starter to Gatsby v2 starter

### PR DESCRIPTION
**Pull request by sidntrivedi**
Since manually migrating the blog from gatsby v1 to v2 was a lot of updations and work, so remade it from gatsby v2 starter. PTAL.

/cc: @osdc/2019-20 @ryzokuken

### CODE REVIEW

**Comment by sidntrivedi** [comment]
It's working fine as of now on the development server. osdcblog

**Comment by sidntrivedi** [comment]
Also, now it's using Yarn instead of npm.

**Comment by nightwarriorftw** [comment]
@sidntrivedi012 LGTM

**Comment by sidntrivedi** [comment]
Deployed at https://osdc-blog.netlify.com . Will be changed to https://osdcblog.netlify.com after deleting the old site.

**Pull request merged**
