### PR TITLE
Remove boilerplate blogposts

### PR DESCRIPTION
**Pull request by ryzokuken**
Removed the old boilerplate blogposts. @vaibhavk @sidntrivedi012 please review.

### CODE REVIEW

**Comment by sidntrivedi** [comment]
Looks great. @ryzokuken .

**Comment by saranshbarua** [comment]
@ryzokuken looks good. Let's merge this.

**Comment by saranshbarua** [comment]
@ryzokuken is it only me who can still see those blog posts?

**Comment by sidntrivedi** [comment]
@saranshbarua No, I can see them too. Something wrong with continuous
integration?

**Comment by ryzokuken** [comment]
@saranshbarua @sidntrivedi012 There is no CI. I'll push it manually.

**Pull request merged**
