### PR TITLE
Fix Whitespace

### PR DESCRIPTION
**Pull request by ryzokuken**
Fixed whitespace issue. @vaibhavk @sidntrivedi012 PTAL.

### CODE REVIEW

**Comment by sidntrivedi** [comment]
Great. Thanks @ryzokuken :)

**Comment by sidntrivedi** [comment]
@ryzokuken , there is one more bug. I wrote the wrong date on the `How to Open Source` blog, please change it.

**Comment by ryzokuken** [comment]
Exactly! I noticed. Please make a PR changing dates to the exact date of
the meet-up.

**Comment by sidntrivedi** [comment]
@ryzokuken Sure.

**Comment by ryzokuken** [comment]
@saranshbarua please review?

**Comment by sidntrivedi** [comment]
@ryzokuken @saranshbarua I guess we can merge this?

**Pull request merged**
